### ISSUE TITLE
Module import error from Octane app

### ISSUE THREAD

**Issue by balinterdi** [buschtoens/ember-link#122]
Trying to use ember-link (version 1.0.1) in an Octane app and I get the following error:

> Could not find module `ember-link/components/link/template` imported from `sac-sac-mate/components/link/template`

I don't think it matters but that's how I try to use it from the template:

```hbs
<Link @route="players.player" @models={{array player}} as |link|>
  <a
   class="no-underline text-blue hover:text-blue-darker w-350px"
   href={{link.href}}>
   <PlayerCard @player={{player}} />
  </a>
</Link>
```

It seems that the problem comes from the addon's merged `app` tree but I'm not sure how to fix it (or whether that's indeed the problem).

**Comment by rwjblue** [comment]
@balinterdi - Mind making a demo repo (or linking to a branch or something)? I'm _guessing_ that the `addon/components/ember-link/template.hbs` is not being processed by the `colocation` branch of `ember-cli-htmlbars` but I'm not sure...

**Comment by balinterdi** [comment]
@rwjblue Sure, the app/branch I'm using it in is here: https://github.com/balinterdi/sac-sac-mate/tree/ember-link . It's not a public repo but I added you as a collaborator.

FWIW, I tried using the latest release of ember-cli-htmlbars to see if that makes a difference but it didn't. I didn't change any other dependency, though, so I'm not sure if that experiment tells us something.

**Comment by buschtoens** [comment]
Are you by any chance using a `podModulePrefix`?

**Comment by buschtoens** [comment]
Ah sorry. This shouldn't matter. The `colocation` thing might be a good hint though. Unfortunately I cannot access your repository.

**Comment by balinterdi** [comment]
@buschtoens Thank you for your reply. I don't use `podModulePrefix`. I added you to the repo if you have time to take a look.

**Comment by balinterdi** [comment]
The latest version of the add-on (1.1.0-beta.5) works great with the first fully-Octane Ember version (3.15.0) so I'll happily close this.

**Comment by buschtoens** [comment]
Awesome! Thank you for following up on this! 💖
