### ISSUE TITLE
Doesn't work in a project with e-decorators v6

### ISSUE THREAD

**Issue by Windvis** [buschtoens/ember-link#51]
We're getting the following console error when using the pre-octane version in an Ember 3.9 + Decorators v6 project:

```
Error: Assertion Failed: computed decorators must return an instance of an Ember ComputedProperty descriptor, received [object Function]
```
I searched the discord and it seems that this is related to the usage of e-decorators v5 in this addon.

Are there any plans for updating the pre-octane version? :) If not, I totally understand. We can always use the `ember-router-helpers` as an (more verbose) alternative.

**Comment by buschtoens** [comment]
The trouble is that `sparkles-component` only works with v5 `ember-decorators` (stage 2). I'll try to refactor the `0.x` series away from `sparkles-component` and then update to v6.

**Comment by buschtoens** [comment]
I published two new releases:

- [`v0.3.0`](https://github.com/buschtoens/ember-link/releases/tag/v0.3.0): Drops `sparkles-component`, but keeps `ember-decorators@5.*` (stage 2 decorators).
- [`v0.4.0`](https://github.com/buschtoens/ember-link/releases/tag/v0.4.0): Drops `sparkles-component` and `ember-decorators` entirely. Uses the vanilla Ember.js decorators via `ember-decorators-polyfill` (stage 1 decorators).

**Comment by Windvis** [comment]
Man... You are insanely fast 🎉 v0.4.0 works like a charm, thanks a lot!

I didn't know sparkles wasn't compatible with v6, that explains all the @tracked errors I was getting 😄in my fork. 

Thanks again, you are a legend!
