### ISSUE TITLE
Handle Cmd / Ctrl click to open in a new tab

### ISSUE THREAD

**Issue by buschtoens** [buschtoens/ember-link#6]
When a link is clicked with <kbd>Cmd</kbd> / <kbd>Ctrl</kbd> it should open in a new tab.

The reason it does not work right now is that we _always_ call [`event.preventDefault()`](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault), if [`@preventDefault`](https://github.com/buschtoens/ember-link#preventdefault) is `true` / unset.

I think there's different solutions to this.

For one, we can add another boolean: `@allowNewTab`
If `true` (default) it will check whether [`event.currentTarget`](https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget) is an `<a>` element and if <kbd>Cmd</kbd> / <kbd>Ctrl</kbd> are pressed, in which case it will _not_ call [`event.preventDefault()`](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault), even if [`@preventDefault`](https://github.com/buschtoens/ember-link#preventdefault) is `true`.

In addition to this, we can also add another action `openInNewTab`, that opens `href` in a new tab.

Big thanks to @tchak13, who reported this via Twitter:
https://twitter.com/tchak13/status/1106149903317852160

**Comment by rtablada** [comment]
@buschtoens In our app we mimicked this code in `ember-href-to` that checks that the left click does not have modifiers.

https://github.com/intercom/ember-href-to/blob/master/addon/href-to.js#L35-L39

**Comment by buschtoens** [comment]
Thanks for the link, @rtablada! 😊

**Comment by buschtoens** [comment]
There's also the possibility of <kbd>Cmd</kbd> or <kbd>Ctrl</kbd> clicking a button, which would open the form submission in a new tab. Contrary to `<a>` I don't think that we would ever want this behavior for `<form>` in Ember, so I guess by default <kbd>Cmd</kbd> or <kbd>Ctrl</kbd> clicking a `<button>` should still be `event.preventDefault()`'ed.

It's probably easiest to understand, if I don't expose yet another flag and just bake all of this (including `@allowNewTab`) into `@preventDefault`. If users need more sophisticated behavior, they can just write their own event handler.

**Comment by buschtoens** [comment]
Released in https://github.com/buschtoens/ember-link/releases/tag/v1.2.1. 🥳
