### ISSUE TITLE
New release that allows `@glimmer/tracking` v1.1.1

### ISSUE THREAD

**Issue by bertdeblock** [buschtoens/ember-link#693]
Hi, would it be possible to cut a new release that contains [this PR](https://github.com/buschtoens/ember-link/pull/678)?
This would avoid people having to use resolutions/overrides.

**Comment by Turbo87** [comment]
I've just pushed v2.0.0 to the repo, which should be released to npm via CI in the next minutes.

**Comment by bertdeblock** [comment]
Super, thanks a lot @Turbo87.
