### ISSUE TITLE
`setupLink()` is broken for engines

### ISSUE THREAD

**Issue by gossi** [buschtoens/ember-link#714]
As we figured, we weren't able to use `setupLink()` from within engines. @buschtoens did a run-down of this (credits to him, I'm just writing it down):

We are hit by this: https://github.com/emberjs/ember.js/issues/11173#issuecomment-124897632

https://github.com/buschtoens/ember-link/blob/2db4148a082a500965ad3be46b70ba6a5ce2673f/addon-test-support/setup-link.ts#L9-L16

places the normal `LinkManagerService` in the `container.cache` and `container.factoryManagerCache`.
Then the following `owner.unregister(…)` apparently only removes the registration, but not the instance in the `container.cache`.

There fix was added to `ApplicationInstance`, but the `owner` in our test is not a fully-fledged `ApplicationInstance`: https://github.com/emberjs/ember.js/pull/12680/files

This seems to be an upstream bug in `@ember/test-helpers`, here is the trace:

We don’t have an `application` in render tests, but a `resolver`, so we hit L57 in
https://github.com/emberjs/ember-test-helpers/blob/a4f710420e8dfba1a4245981483d7cbb5dcc865e/addon-test-support/%40ember/test-helpers/build-owner.ts#L41-L60

Which then builds a registry and owner on its own terms.
https://github.com/emberjs/ember-test-helpers/blob/a4f710420e8dfba1a4245981483d7cbb5dcc865e/addon-test-support/@ember/test-helpers/-internal/build-registry.ts

This of course lacks the `unregister` patch:
https://github.com/emberjs/ember.js/blob/0da7fedd3767668e7fb01b50757f1a636782fb54/packages/%40ember/engine/instance.ts#L162-L167

**Comment by buschtoens** [comment]
Thanks for copying this over and also thanks for prepping a PR. 😊

Since I consider this a bug in `@ember/test-helpers`, I've sent in this PR to fix it upstream: https://github.com/emberjs/ember-test-helpers/pull/1216

Hopefully it will be accepted, then we can skip #715. Still thank you for working on this. 🙏

**Comment by buschtoens** [comment]
My PR was merged and released as `2.8.0`.
