### ISSUE TITLE
Types not working on "ember-link": "^3.0.0",

### ISSUE THREAD

**Issue by esbanarango** [buschtoens/ember-link#777]
Types are not working on `"ember-link": "^3.0.0",`

<img width="1128" alt="Cursor_and_responsible-sourcing_ts_—_Untitled__Workspace_" src="https://github.com/buschtoens/ember-link/assets/1156865/0f598a31-c8ec-4fe2-824e-0bb6b64663ba">

Currently using: `"typescript": "5.1.6",`

**Comment by esbanarango** [comment]
Looks like the proper way to import it is:

```ts
import type LinkManagerService from 'ember-link/dist/services/link-manager';
```

**Comment by gossi** [comment]
in your `tsconfig.json` you need to change `moduleResolution` to make TS understand the new `exports` field.

As of TS v4.7 you can use `nodenext` and `node16`, as of TS v5.0 you can and should use `bundler`. This is what `@tsconfig/ember` migrated over as well.

**Comment by esbanarango** [comment]
@gossi Thank you. It did work. Btw, how do you ship types for this moduleResolution (`bundler`)?

**Comment by gossi** [comment]
Using [`exports`](https://nodejs.org/api/packages.html#package-entry-points) entry point, see here: https://github.com/buschtoens/ember-link/blob/bb834b23dd3a79a9c5acbd098c96b31b93ef70f8/ember-link/package.json#L23-L33

Which is the default case to export types (over `typesVersion`).
